# Generated by Django 3.0.3 on 2020-02-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20200226_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
