# Generated by Django 3.0.3 on 2020-02-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20200221_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_image',
        ),
    ]
