# Generated by Django 3.0.3 on 2020-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_remove_product_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
